### ISSUE TITLE
Ошибка при создании документа "Банк/касса"

### ISSUE THREAD

**Issue by Bormaglod** [Bormaglod/DocumentFlow#41]
При создании нового документа выдается ошибка:
Подробная информация об использовании оперативной 
(JIT) отладки вместо данного диалогового 
окна содержится в конце этого сообщения.

************** Текст исключения **************
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'input')
   at System.Text.RegularExpressions.ThrowHelper.ThrowArgumentNullException(ExceptionArgument arg)
   at System.Text.RegularExpressions.Regex.Replace(String input, MatchEvaluator evaluator)
   at System.Text.RegularExpressions.Regex.Replace(String input, String pattern, MatchEvaluator evaluator)
   at Humanizer.InflectorExtensions.Pascalize(String input) in /_/src/Humanizer/InflectorExtensions.cs:line 74
   at DocumentFlow.Entities.PaymentOrders.PaymentOrder.get_PaymentDirection()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at DocumentFlow.Controls.PageContents.Editor`1.RefreshData(Nullable`1 id, Boolean refreshNestedBrowsers)
   at DocumentFlow.Controls.PageContents.Editor`1.SetEntityParameters(Nullable`1 id, Nullable`1 owner_id, Nullable`1 parent_id, Boolean readOnly)
   at DocumentFlow.PageManager.ShowEditor(Type browserType, Nullable`1 objectId, Nullable`1 owner_id, Nullable`1 parentId, Boolean readOnly)
   at DocumentFlow.Controls.PageContents.Browser`1.ShowEditor(T editableRow)
   at DocumentFlow.Controls.PageContents.Browser`1.ButtonCreate_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**Comment by Bormaglod** [comment]
Исправлено в версии 2022.8.16
